// export data to be used in the map
export const MarkerData = () => [
  {
    coordinate: { latitude: 13.7589, longitude: 100.502 },
    title: 'ช่างฉาบ',
    description: 'สถานที่ 1',
    header: 'ช่างฉาบ',
    detail: '฿250',
    image: require('./assets/plumber.png'),
  },
  {
    coordinate: { latitude: 13.7596, longitude: 100.5025 },
    title: 'ช่างไฟ',
    description: 'สถานที่ 2',
    header: 'ช่างไฟ',
    detail: '฿350',
    image: require('./assets/plumber.png'),
  },
  {
    coordinate: { latitude: 13.7596, longitude: 100.5035 },
    title: 'แม่บ้าน',
    description: 'สถานที่ 3',
    header: 'แม่บ้าน',
    detail: '฿350',
    image: require('./assets/cleaner.png'),
  },
  {
    coordinate: { latitude: 13.7587, longitude: 100.5045 },
    title: 'ช่างภาพ',
    description: 'โรงแรม',
    header: 'ช่างภาพ',
    detail: '฿1500',
    image: require('./assets/photographer.png'),
  },
  {
    coordinate: { latitude: 13.7591, longitude: 100.5055 },
    title: 'ช่างภาพ',
    description: 'โรงแรม',
    header: 'ช่างภาพ',
    detail: '฿1500',
    image: require('./assets/photographer.png'),
  },
  {
    coordinate: { latitude: 13.7595, longitude: 100.5065 },
    title: 'ช่างภาพ',
    description: 'โรงแรม',
    header: 'ช่างภาพ',
    detail: '฿1500',
    image: require('./assets/photographer.png'),
  },
  {
    coordinate: { latitude: 13.7597, longitude: 100.5075 },
    title: 'ช่างภาพ',

    description: 'โรงแรม',
    header: 'ช่างภาพ',
    detail: '฿1500',
    image: require('./assets/photographer.png'),
  },
  {
    coordinate: { latitude: 13.7596, longitude: 100.5025 },
    title: 'ช่างไฟ',
    description: 'สถานที่ 2',
    header: 'ช่างไฟ',
    detail: '฿350',
    image: require('./assets/plumber.png'),
  },
  {
    coordinate: { latitude: 13.7596, longitude: 100.5035 },
    title: 'แม่บ้าน',
    description: 'สถานที่ 3',
    header: 'แม่บ้าน',
    detail: '฿350',
    image: require('./assets/cleaner.png'),
  },
];
